language: objective-c
script:
  - xctool -workspace TCUTools.xcworkspace -scheme TCUTools -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace TCUTools.xcworkspace -scheme Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO