source 'https://github.com/CocoaPods/Specs.git'

target 'TCUTools', :exclusive => true do
  pod "TCUTools", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TCUTools", :path => "../"
end
